// flow-typed signature: d01b3d96010c2e444d248d27924a0035
// flow-typed version: <<STUB>>/scrape-it_v^3.3.2/flow_v0.44.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'scrape-it'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'scrape-it' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'scrape-it/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'scrape-it/lib/index.js' {
  declare module.exports: $Exports<'scrape-it/lib/index'>;
}
